// skills/fe-codegen-workbench/references/components/react-virtual-paginated-select/components/VirtualTable.example.tsx
import React, { useMemo, useCallback } from 'react';
import { FixedSizeList as List } from 'react-window';
import { Spin, Empty } from 'antd';
import type { VirtualTableProps, VirtualTableRow, VirtualTableColumn } from '../types.example';
import './VirtualTable.less';

/**
 * 虚拟滚动表格组件
 * 
 * 特性：
 * 1. 大数据量高性能渲染（8000+ 行）
 * 2. 固定行高虚拟滚动
 * 3. 支持单元格内编辑
 * 4. 支持固定列（左/右）
 */
const VirtualTable = <T extends VirtualTableRow = VirtualTableRow>({
  data,
  columns,
  rowHeight = 60,
  height = 500,
  width = '100%',
  headerHeight = 48,
  loading = false,
  rowKey = 'rowKey',
  onRowClick,
}: VirtualTableProps<T>) => {
  // 获取行 key
  const getRowKey = useCallback(
    (row: T, index: number): string => {
      if (typeof rowKey === 'function') {
        return rowKey(row);
      }
      return row[rowKey] || String(index);
    },
    [rowKey]
  );

  // 计算列宽
  const columnWidths = useMemo(() => {
    const containerWidth = typeof width === 'number' ? width : 1000;
    const fixedWidth = columns.reduce((sum, col) => sum + (col.width || 0), 0);
    const flexColumns = columns.filter((col) => !col.width);
    const flexWidth = (containerWidth - fixedWidth) / (flexColumns.length || 1);

    return columns.map((col) => col.width || Math.max(col.minWidth || 100, flexWidth));
  }, [columns, width]);

  // 渲染表头
  const renderHeader = () => (
    <div className="virtual-table-header" style={{ height: headerHeight }}>
      {columns.map((col, index) => (
        <div
          key={col.key}
          className={`virtual-table-header-cell ${col.fixed ? `fixed-${col.fixed}` : ''}`}
          style={{
            width: columnWidths[index],
            minWidth: col.minWidth,
            textAlign: col.align || 'left',
          }}
        >
          {col.title}
        </div>
      ))}
    </div>
  );

  // 渲染行
  const Row = useCallback(
    ({ index, style }: { index: number; style: React.CSSProperties }) => {
      const row = data[index];
      const key = getRowKey(row, index);

      return (
        <div
          key={key}
          className={`virtual-table-row ${index % 2 === 0 ? 'even' : 'odd'}`}
          style={style}
          onClick={() => onRowClick?.(row, index)}
        >
          {columns.map((col, colIndex) => {
            const cellContent = col.cellRenderer
              ? col.cellRenderer({ rowData: row, rowIndex: index, column: col })
              : row[col.dataKey] ?? '--';

            return (
              <div
                key={col.key}
                className={`virtual-table-cell ${col.fixed ? `fixed-${col.fixed}` : ''}`}
                style={{
                  width: columnWidths[colIndex],
                  minWidth: col.minWidth,
                  textAlign: col.align || 'left',
                }}
              >
                {cellContent}
              </div>
            );
          })}
        </div>
      );
    },
    [data, columns, columnWidths, getRowKey, onRowClick]
  );

  // 空状态
  if (!loading && data.length === 0) {
    return (
      <div className="virtual-table-empty" style={{ height }}>
        <Empty description="暂无数据" />
      </div>
    );
  }

  return (
    <Spin spinning={loading}>
      <div className="virtual-table" style={{ width }}>
        {renderHeader()}
        <List
          height={height - headerHeight}
          itemCount={data.length}
          itemSize={rowHeight}
          width="100%"
          className="virtual-table-body"
        >
          {Row}
        </List>
      </div>
    </Spin>
  );
};

export default VirtualTable;

// skills/fe-codegen-workbench/references/components/vue2-virtual-paginated-select/components/VirtualTable.example.vue
<template>
  <div class="virtual-table" :style="{ width: tableWidth }">
    <!-- 表头 -->
    <div class="virtual-table-header" :style="{ height: headerHeight + 'px' }">
      <div
        v-for="(col, index) in columns"
        :key="col.key"
        class="virtual-table-header-cell"
        :class="{ [`fixed-${col.fixed}`]: col.fixed }"
        :style="{
          width: getColumnWidth(col, index) + 'px',
          textAlign: col.align || 'left',
        }"
      >
        {{ col.title }}
      </div>
    </div>

    <!-- 虚拟滚动列表 -->
    <RecycleScroller
      v-if="data.length > 0"
      ref="scroller"
      class="virtual-table-body"
      :items="data"
      :item-size="rowHeight"
      :key-field="rowKeyField"
      :style="{ height: bodyHeight + 'px' }"
      v-slot="{ item, index }"
    >
      <div
        class="virtual-table-row"
        :class="{ even: index % 2 === 0, odd: index % 2 !== 0 }"
        @click="$emit('row-click', item, index)"
      >
        <div
          v-for="(col, colIndex) in columns"
          :key="col.key"
          class="virtual-table-cell"
          :class="{ [`fixed-${col.fixed}`]: col.fixed }"
          :style="{
            width: getColumnWidth(col, colIndex) + 'px',
            textAlign: col.align || 'left',
          }"
        >
          <!-- 使用作用域插槽自定义单元格 -->
          <slot
            :name="`cell-${col.key}`"
            :row="item"
            :column="col"
            :index="index"
          >
            {{ getCellValue(item, col) }}
          </slot>
        </div>
      </div>
    </RecycleScroller>

    <!-- 空状态 -->
    <div v-else class="virtual-table-empty" :style="{ height: bodyHeight + 'px' }">
      <slot name="empty">
        <el-empty description="暂无数据" />
      </slot>
    </div>

    <!-- 加载遮罩 -->
    <div v-if="loading" class="virtual-table-loading">
      <i class="el-icon-loading"></i>
      <span>加载中...</span>
    </div>
  </div>
</template>

<script>
import { RecycleScroller } from 'vue-virtual-scroller';
import 'vue-virtual-scroller/dist/vue-virtual-scroller.css';

export default {
  name: 'VirtualTable',
  components: {
    RecycleScroller,
  },
  props: {
    data: {
      type: Array,
      default: () => [],
    },
    columns: {
      type: Array,
      required: true,
    },
    rowHeight: {
      type: Number,
      default: 60,
    },
    height: {
      type: Number,
      default: 500,
    },
    width: {
      type: [Number, String],
      default: '100%',
    },
    headerHeight: {
      type: Number,
      default: 48,
    },
    loading: {
      type: Boolean,
      default: false,
    },
    rowKey: {
      type: String,
      default: 'rowKey',
    },
  },
  computed: {
    tableWidth() {
      return typeof this.width === 'number' ? `${this.width}px` : this.width;
    },
    bodyHeight() {
      return this.height - this.headerHeight;
    },
    rowKeyField() {
      return this.rowKey;
    },
    containerWidth() {
      return typeof this.width === 'number' ? this.width : 1000;
    },
  },
  methods: {
    getColumnWidth(col, index) {
      if (col.width) return col.width;

      const fixedWidth = this.columns.reduce((sum, c) => sum + (c.width || 0), 0);
      const flexColumns = this.columns.filter((c) => !c.width);
      const flexWidth = (this.containerWidth - fixedWidth) / (flexColumns.length || 1);

      return Math.max(col.minWidth || 100, flexWidth);
    },
    getCellValue(row, col) {
      const value = row[col.dataKey];
      return value !== undefined && value !== null ? value : '--';
    },
  },
};
</script>

<style scoped lang="less">
.virtual-table {
  position: relative;
  border: 1px solid #ebeef5;
  border-radius: 4px;
  overflow: hidden;

  &-header {
    display: flex;
    background: #fafafa;
    border-bottom: 1px solid #ebeef5;
    font-weight: 500;
  }

  &-header-cell {
    padding: 12px 16px;
    display: flex;
    align-items: center;
    border-right: 1px solid #ebeef5;
    flex-shrink: 0;
    box-sizing: border-box;

    &:last-child {
      border-right: none;
    }

    &.fixed-left {
      position: sticky;
      left: 0;
      background: #fafafa;
      z-index: 2;
    }

    &.fixed-right {
      position: sticky;
      right: 0;
      background: #fafafa;
      z-index: 2;
    }
  }

  &-body {
    overflow-x: hidden !important;
  }

  &-row {
    display: flex;
    border-bottom: 1px solid #ebeef5;
    transition: background-color 0.2s;
    cursor: pointer;

    &:hover {
      background: #f5f7fa;
    }

    &.even {
      background: #fff;
    }

    &.odd {
      background: #fafafa;
    }
  }

  &-cell {
    padding: 8px 16px;
    display: flex;
    align-items: center;
    border-right: 1px solid #ebeef5;
    flex-shrink: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    box-sizing: border-box;

    &:last-child {
      border-right: none;
    }

    &.fixed-left {
      position: sticky;
      left: 0;
      background: inherit;
      z-index: 1;
    }

    &.fixed-right {
      position: sticky;
      right: 0;
      background: inherit;
      z-index: 1;
    }
  }

  &-empty {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  &-loading {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(255, 255, 255, 0.8);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 8px;
    z-index: 10;

    i {
      font-size: 24px;
      color: #409eff;
    }

    span {
      color: #606266;
    }
  }
}
</style>
